
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-purple-900 via-black to-gray-900`}>
        <header className="text-yellow-300 body-font">
          <div className="container mx-auto flex flex-wrap p-4 flex-col md:flex-row items-center">
            <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
              <div className="avatar">
                <Image
                  src="/mak logo.png"
                  alt="logo"
                  width={80}
                  height={80}
                  className="ring-primary ring-offset-base-100 w-20 rounded-full ring ring-offset-2 shadow-neonBlue" />
              </div>
              <h1 className="ml-3 text-4xl font-serif font-bold text-neonPink hover:text-white transition-all duration-500 animate-glow">
                <span className="text-pink-600 text-5xl hover:text-white">P</span>ortFolio
              </h1>
            </a>
            <nav className="md:ml-auto md:mr-auto flex flex-wrap items-center justify-center text-2xl gap-7 font-sans font-semibold animate-pulse">
              <Link href="/" className="transform hover:scale-110 hover:text-neonPink">Home</Link>
              <Link href="/about" className="transform hover:scale-110 hover:text-neonPink">About</Link>
              <Link href="/skills" className="transform hover:scale-110 hover:text-neonPink">Skills</Link>
              <Link href="/projects" className="transform hover:scale-110 hover:text-neonPink">Projects</Link>
              <Link href="/services" className="transform hover:scale-110 hover:text-neonPink">Services</Link>
              <Link href="/contact" className="transform hover:scale-110 hover:text-neonPink">Contact</Link>
            </nav>
          </div>
        </header>
        {children}
        <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1" async></script>
      </body>
    </html>
  );
}
